/* Auto-generated from memtypes.c by gawk. */
/* Do not edit! */

#ifndef _QUAGGA_MEMTYPES_H
#define _QUAGGA_MEMTYPES_H

enum
{
  MTYPE_VECTOR,
  MTYPE_VECTOR_INDEX,
  MTYPE_LINK_LIST,
  MTYPE_LINK_NODE,
  MTYPE_HASH,
  MTYPE_HASH_BACKET,
  MTYPE_HASH_INDEX,
  MTYPE_PEER_ID,
  MTYPE_SOCKUNION,
  MTYPE_MISAKA_PEER,
  MTYPE_MISAKA_MID,
  MTYPE_MISAKA_DATA,
  MTYPE_STREAM,
  MTYPE_STREAM_FIFO,
  MTYPE_STREAM_DATA,
  MTYPE_MAX,
};

#endif /* _QUAGGA_MEMTYPES_H */

